# Generated by Django 2.0.9 on 2018-10-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo', models.CharField(max_length=200)),
                ('Rut', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=200)),
                ('FechaNac', models.DateTimeField(blank=True, null=True)),
                ('Region', models.CharField(max_length=200)),
                ('Ciudad', models.CharField(max_length=200)),
                ('Vivienda', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Raza', models.CharField(max_length=200)),
                ('Descripcion', models.TextField(max_length=200)),
                ('Estado', models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], max_length=20)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%D/')),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
