# Generated by Django 2.0.9 on 2018-10-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo', models.CharField(max_length=200)),
                ('Rut', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=200)),
                ('FechaNac', models.DateTimeField(blank=True, null=True)),
                ('Telefono', models.CharField(max_length=10)),
                ('Region', models.CharField(max_length=200)),
                ('Ciudad', models.CharField(max_length=200)),
                ('Vivienda', models.CharField(choices=[('Casa con patio Grande', 'Casa con patio Grande'), ('Casa con patio pequeño', 'Casa con patio pequeño'), ('Casa sin patio', 'Casa sin patio'), ('Departamento', 'Departamento')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Raza', models.CharField(max_length=200)),
                ('Descripcion', models.TextField(max_length=200)),
                ('Estado', models.CharField(choices=[('Rescatado', 'rescatado'), ('Disponible', 'disponible'), ('Adoptado', 'adoptado')], max_length=20)),
                ('Imagen', models.ImageField(upload_to='')),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
