# Generated by Django 2.0.9 on 2018-10-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perriBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='Estado',
            field=models.CharField(choices=[('Rescatado', 'rescatado'), ('Disponible', 'disponible'), ('Adoptado', 'adoptado')], max_length=20),
        ),
    ]
